name: multiple jobs workflow

on:
  workflow_dispatch:

#job 1
jobs:
  ubuntu-os-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: print the os name
        run:  echo "The operating system is ${{ runner.os }}"

      - name: print the hostname 
        run: hostname

      - name: get current user running the job
        run: whoami

      - name: get docker version
        run: docker --version

      - name: get python version
        run: python --version

      - name: get node vresion
        run: node --version

      - name: get git version
        run: git --version
    

  windows-job: 
      runs-on: windows-latest

      steps:
       - name: print os name
         run: echo "The operating system is ${{ runner.os }}"

       - name: print hostname
         run: hostname

       - name: get current user running the job
         run: whoami


  mac-os-workflow:
    runs-on: macos-latest

    steps:
      - name: print name of os
        run: echo "The operating system is ${{ runner.os }}"

      - name: get host name
        run:  hostname

      - name: get the user running the job
        run:  whoami
        
