name: manual trigger workflow

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose environment (staging or production)"
        required: true
        default: staging


jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: print environment
        run: echo "Selected environment is ${{ github.event.inputs.environment }}"
