name: multi jobs workflows

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: print Building the app
        run: echo app installed

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: print Running tests
        run: echo Running tests

  deploy:
    needs: test
    runs-on: ubuntu-latest

  steps:
    - name: print deploying
      run: echo print deploying 

    

    

    
