name: self hosted workflow

on: 
  push:

jobs:
  self-hosted-workflow:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: print the hostname
        run: hostname

      - name: print current working directory
        run:  cd

      - name: create a file 
        run: ew-Item myfile.txt -ItemType File

      - name: verify the file exists 
        run: Test-Path myfile.txt 
